import SettingSection from "@/components/frontend/ui/customer/SettingSection";
export const metadata = {
  title: "Setting",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const SettingPage = () => {
  return (
    <div>
      <SettingSection />
    </div>
  );
};

export default SettingPage;
