export const metadata = {
  title: {
    default: "Auth",
    template: "%s - Janani Computer",
  },
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};
export default function AuthLayout({ children }) {
  return <div>{children}</div>;
}
