import AboutUs from "@/components/frontend/ui/aboutus/AboutUs";
import { getSettingData } from "@/lib/getSettingData";

export const metadata = {
  title: "About Us",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const AboutUsPage = async () => {
  const aboutUsData = await getSettingData();
  return (
    <div className="container pb-5">
      <AboutUs aboutData={aboutUsData?.data[0]?.about_us} />
    </div>
  );
};

export default AboutUsPage;
