import AccountSection from "@/components/frontend/ui/customer/AccountSection";
export const metadata = {
  title: "Account",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const AccountPage = () => {
  return (
    <div>
      <AccountSection />
    </div>
  );
};

export default AccountPage;
