import { getPcBuilderCategoryData } from "@/lib/getPcBuilderCategoryData";
import PcBuilderMainSection from "@/components/frontend/ui/pcbuilder/PcBuilderMainSection";
export const metadata = {
  title: "Pc Builder",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const PcBuilderPage = async () => {
  const pcBuilderCategoryData = await getPcBuilderCategoryData();
  return (
    <div className="container py-1 md:py-3">
      <PcBuilderMainSection
        pcBuilderCategoryData={pcBuilderCategoryData?.data}
      />
    </div>
  );
};

export default PcBuilderPage;
