import WishlistSection from "@/components/frontend/ui/wishlist/WishlistSection";

export const metadata = {
  title: "Wishlist",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const WishlistPage = () => {
  return (
    <div className="container">
      <WishlistSection />
    </div>
  );
};

export default WishlistPage;
