import AllBranch from "@/components/frontend/ui/allbranch/AllBranch";
import { getSettingData } from "@/lib/getSettingData";
export const metadata = {
  title: "All Branch",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const AllBranchPage = async () => {
  const allBranchData = await getSettingData();
  return (
    <div className="container pb-5">
      <AllBranch allBranchData={allBranchData?.data[0]?.all_branch} />
    </div>
  );
};

export default AllBranchPage;
