import { getFlashData } from "@/lib/getFlashData";
import FlashSaleSection from "@/components/frontend/ui/flashsale/FlashSaleSection";

export const metadata = {
  title: "Flash Sale",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const FlashSalePage = async () => {
  const flashData = await getFlashData();
  return (
    <div className="container">
      <FlashSaleSection campaign={flashData?.data} />
    </div>
  );
};

export default FlashSalePage;
