import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-tooltip/dist/react-tooltip.css";
import { Poppins } from "next/font/google";
import Providers from "@/components/lib/Providers";
import AuthProvider from "@/provider/AuthProvider";
import QueryProviders from "@/components/lib/QueryProviders";
import { Slide, ToastContainer } from "react-toastify";
import ScrollToTop from "@/shared/ScrollToTop";
import "react-loading-skeleton/dist/skeleton.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});
export const metadata = {
  title: {
    default: "Home",
    template: "%s - Janani Computer",
  },
  description: "Generated by Masud Rana",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Providers>
          <AuthProvider>
            <QueryProviders>
              <main>
                {children}
                <ToastContainer
                  position="bottom-right"
                  autoClose={1500}
                  transition={Slide}
                  closeOnClick
                />
                <ScrollToTop />
              </main>
            </QueryProviders>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
