import { getOfferData } from "@/lib/getOfferData";
import MainOfferSection from "@/components/frontend/ui/offer/MainOfferSection";
export const metadata = {
  title: "Offer",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};
const OfferPage = async () => {
  const offerData = await getOfferData();
  return (
    <div className="container">
      <MainOfferSection offerData={offerData?.data} />
    </div>
  );
};

export default OfferPage;
