import { getSettingData } from "@/lib/getSettingData";
import SupportPolicy from "@/components/frontend/ui/supportpolicy/SupportPolicy";
export const metadata = {
  title: "Support Policy",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const SupportPolicyPage = async () => {
  const supportPolicyData = await getSettingData();
  return (
    <div className="container pb-5">
      <SupportPolicy
        supportPolicyData={supportPolicyData?.data[0]?.privacy_policy}
      />
    </div>
  );
};

export default SupportPolicyPage;
