import CustomerSection from "@/components/frontend/ui/customer/CustomerSection";

export const metadata = {
  title: "My Order",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const CustomerDashboardPage = () => {
  return (
    <div className="container">
      <CustomerSection />
    </div>
  );
};

export default CustomerDashboardPage;
