export const metadata = {
  title: "Invoice",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};
export default function InvoiceLayout({ children }) {
  return <div>{children}</div>;
}
