import OrderTracking from "@/components/frontend/ui/order/OrderTracking";
export const metadata = {
  title: "Order Tracking",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const OrderTrackingPage = () => {
  return (
    <div className="container py-5">
      <OrderTracking />
    </div>
  );
};

export default OrderTrackingPage;
