import { Suspense } from "react";
import Skeleton from "react-loading-skeleton";
import { getMenuData } from "@/lib/getMenuData";
import { getBannerData } from "@/lib/getBannerData";
import { getFeatureData } from "@/lib/getFeatureData";
import { getFeatureProductsData } from "@/lib/getFeatureProductData";
import { getExploreProductsData } from "@/lib/getExploreProductData";
import { getHotDealProductsData } from "@/lib/getHotDealProductData";
import { getFeatureCategoryData } from "@/lib/getFeatureCategoryData";
import ProductSkeleton from "@/components/common/loader/ProductSkeleton";
import TopCategory from "../../components/frontend/ui/topcategory/TopCategory";
import CategorySection from "@/components/frontend/ui/category/CategorySection";
import MainBestProducts from "@/components/frontend/ui/products/MainBestProducts";
import MainHeroSection from "@/components/frontend/ui/herosection/MainHeroSection";
import MainFeatureProducts from "@/components/frontend/ui/products/MainFeatureProducts";
import FeatureSection from "../../components/frontend/ui/featuresection/FeatureSection";
import FeatureCategorySkeleton from "@/components/frontend/ui/skeleton/FeatureCategorySkeleton";

export const metadata = {
  title: {
    absolute: "Home - Janani Computer",
  },
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const Home = () => {
  const promiseMenuData = getMenuData();
  const promiseBannerData = getBannerData();
  const promiseFeatureData = getFeatureData();
  const promiseFeatureProductData = getFeatureProductsData();
  const promiseFeatureCategoryData = getFeatureCategoryData();
  const promiseExploreProductsData = getExploreProductsData();
  const promiseHotDealProductsData = getHotDealProductsData();

  return (
    <>
      <Suspense
        fallback={
          <div className="container">
            <Skeleton count={5} />
          </div>
        }
      >
        <MainHeroSection
          promiseBannerData={promiseBannerData}
          promiseMenuData={promiseMenuData}
        />
      </Suspense>
      <FeatureSection promiseFeatureData={promiseFeatureData} />
      <Suspense
        fallback={
          <div className="container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-x-3 gap-y-3 lg:gap-y-5">
            {Array.from(Array(12).keys()).map((i) => (
              <FeatureCategorySkeleton key={i} />
            ))}
          </div>
        }
      >
        <TopCategory promiseFeatureCategoryData={promiseFeatureCategoryData} />
      </Suspense>
      <Suspense
        fallback={
          <div className="container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-x-3 gap-y-3 lg:gap-y-5">
            {Array.from(Array(12).keys()).map((i) => (
              <ProductSkeleton key={i} />
            ))}
          </div>
        }
      >
        <CategorySection
          promiseExploreProductsData={promiseExploreProductsData}
        />
      </Suspense>
      <Suspense
        fallback={
          <div className="container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-x-3 gap-y-3 lg:gap-y-5">
            {Array.from(Array(12).keys()).map((i) => (
              <ProductSkeleton key={i} />
            ))}
          </div>
        }
      >
        <MainFeatureProducts
          promiseFeatureProductData={promiseFeatureProductData}
        />
      </Suspense>
      <Suspense
        fallback={
          <div className="container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-x-3 gap-y-3 lg:gap-y-5">
            {Array.from(Array(12).keys()).map((i) => (
              <ProductSkeleton key={i} />
            ))}
          </div>
        }
      >
        <MainBestProducts
          promiseHotDealProductsData={promiseHotDealProductsData}
        />
      </Suspense>
    </>
  );
};

export default Home;
