import MainCompare from "@/components/frontend/ui/compare/MainCompare";
export const metadata = {
  title: "Compare",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const ComparePage = () => {
  return (
    <div className="container px-0">
      <MainCompare />
    </div>
  );
};

export default ComparePage;
