import MyOrderTracking from "@/components/frontend/ui/order/MyOrderTracking";

export const metadata = {
  title: "My Order Tracking",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const MyOrderTrackingPage = () => {
  return (
    <div className="container">
      <MyOrderTracking />
    </div>
  );
};

export default MyOrderTrackingPage;
