import { getSettingData } from "@/lib/getSettingData";
import ReturnPolicy from "@/components/frontend/ui/returnpolicy/ReturnPolicy";
export const metadata = {
  title: "Return Policy",
  description: "Generated by Masud Rana",
  authors: {
    name: "Masud Rana",
    url: "https://www.facebook.com/masudranawebdev",
  },
};

const ReturnPolicyPage = async () => {
  const returnPolicyData = await getSettingData();
  return (
    <div className="container pb-5">
      <ReturnPolicy
        returnPolicyData={returnPolicyData?.data[0]?.privacy_policy}
      />
    </div>
  );
};

export default ReturnPolicyPage;
